name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        uv venv
        source .venv/bin/activate # Activate venv for subsequent uv commands in the same step
        uv pip install .[dev]

    - name: Check formatting with Ruff
      run: |
        source .venv/bin/activate
        uv run ruff format --check .

    - name: Lint with Ruff
      run: |
        source .venv/bin/activate
        uv run ruff check .
